### ISSUE TITLE
publish 1.1.1 to npm

### ISSUE THREAD

**Issue by dominicbarnes** [component/spinner#7]
I had to update to fix for component (supported.js needed to be added to `scripts`) but I was unable to publish to npm

**Comment by TooTallNate** [comment]
published 1.1.1 and added `dominicbarnes` as an npm owner.

**Comment by dominicbarnes** [comment]
Thanks!

**Comment by TooTallNate** [comment]
Sorry about that oversight btw!

**Comment by dominicbarnes** [comment]
No worries!
